###register request
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "username":"test",
    "email":"test@gmail.com",
    "mobile":"09190000000",
    "password":"123456",
    "confirm_password":"123456"
}
###login request
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json
Authorization:  Bearer {{$dotenv token}}

{
    "username":"naser",
    "password":"123456"
}
###logout request
GET  http://127.0.0.1:5000/auth/logout
Content-Type: application/json
Authorization:  Bearer {{$dotenv token}}
